-- ============================================
-- NBT-Tasker: Combined SQL Setup Script
-- Run this ONCE in Supabase SQL Editor
-- ============================================

-- Enable pg_trgm extension (for fuzzy search)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================
-- 1. TABLES
-- ============================================

DROP FUNCTION IF EXISTS requesting_user_id() CASCADE;
DROP FUNCTION IF EXISTS get_boards_for_authenticated_user() CASCADE;
DROP FUNCTION IF EXISTS handle_board_added() CASCADE;
DROP FUNCTION IF EXISTS notify_user() CASCADE;
DROP FUNCTION IF EXISTS search_users(VARCHAR) CASCADE;

CREATE OR REPLACE FUNCTION requesting_user_id()
RETURNS TEXT AS $$
    SELECT auth.jwt() ->> 'sub';
$$ LANGUAGE SQL STABLE;

DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS user_boards CASCADE;
DROP TABLE IF EXISTS card_labels CASCADE;
DROP TABLE IF EXISTS labels CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS checklist_items CASCADE;
DROP TABLE IF EXISTS checklists CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS lists CASCADE;
DROP TABLE IF EXISTS boards CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Create users table
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT,
    first_name TEXT,
    email TEXT,
    avatar_url TEXT,
    push_token TEXT
);

-- Create boards table
CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator TEXT NOT NULL REFERENCES users (id),
    title TEXT DEFAULT 'Untitled Board',
    background TEXT DEFAULT '#126CB3',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_edit TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Many to many table for user <-> boards relationship
CREATE TABLE user_boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    board_id BIGINT REFERENCES boards ON DELETE CASCADE
);

-- Create lists table
CREATE TABLE lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT REFERENCES boards ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT '',
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create cards table
CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id BIGINT REFERENCES lists ON DELETE CASCADE NOT NULL,
    board_id BIGINT REFERENCES boards ON DELETE CASCADE NOT NULL,
    position INT NOT NULL DEFAULT 0,
    title TEXT DEFAULT '',
    description TEXT CHECK (char_length(description) > 0),
    assigned_to TEXT REFERENCES users (id),
    due_date TIMESTAMP WITH TIME ZONE,
    done BOOLEAN DEFAULT FALSE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create checklists table
CREATE TABLE checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES cards ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT 'Checklist',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create checklist_items table
CREATE TABLE checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT REFERENCES checklists ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT '',
    done BOOLEAN DEFAULT FALSE,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create comments table
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES cards ON DELETE CASCADE NOT NULL,
    user_id TEXT NOT NULL REFERENCES users (id),
    text TEXT NOT NULL CHECK (char_length(text) > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create labels table
CREATE TABLE labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT REFERENCES boards ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT '',
    color TEXT DEFAULT '#3B82F6',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create card_labels table
CREATE TABLE card_labels (
    card_id BIGINT REFERENCES cards ON DELETE CASCADE NOT NULL,
    label_id BIGINT REFERENCES labels ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (card_id, label_id)
);

-- Make sure deleted records are included in realtime
ALTER TABLE cards REPLICA IDENTITY FULL;
ALTER TABLE lists REPLICA IDENTITY FULL;
ALTER TABLE checklists REPLICA IDENTITY FULL;
ALTER TABLE checklist_items REPLICA IDENTITY FULL;
ALTER TABLE comments REPLICA IDENTITY FULL;
ALTER TABLE labels REPLICA IDENTITY FULL;
ALTER TABLE card_labels REPLICA IDENTITY FULL;

ALTER PUBLICATION supabase_realtime ADD TABLE cards;
ALTER PUBLICATION supabase_realtime ADD TABLE lists;
ALTER PUBLICATION supabase_realtime ADD TABLE checklists;
ALTER PUBLICATION supabase_realtime ADD TABLE checklist_items;
ALTER PUBLICATION supabase_realtime ADD TABLE comments;
ALTER PUBLICATION supabase_realtime ADD TABLE labels;
ALTER PUBLICATION supabase_realtime ADD TABLE card_labels;

-- Function to get all user boards
CREATE OR REPLACE FUNCTION get_boards_for_authenticated_user()
RETURNS SETOF BIGINT
LANGUAGE SQL
SECURITY DEFINER
SET search_path = ''
STABLE
AS $$
    SELECT board_id
    FROM public.user_boards
    WHERE user_id = public.requesting_user_id()
$$;

-- ============================================
-- 2. SECURITY (RLS Policies)
-- ============================================

-- boards row level security
ALTER TABLE boards ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Users can create boards" ON boards;
    DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON boards;
    DROP POLICY IF EXISTS "Creators can insert boards" ON boards;
END $$;
CREATE POLICY "Users can create boards" ON boards FOR
  INSERT TO public WITH CHECK (COALESCE(requesting_user_id(), 'none') = creator);

DO $$ BEGIN
    DROP POLICY IF EXISTS "Users can view their boards" ON boards;
    DROP POLICY IF EXISTS "Allow select for owners" ON boards;
    DROP POLICY IF EXISTS "Users can view boards" ON boards;
END $$;
CREATE POLICY "Users can view their boards" ON boards FOR
    SELECT USING (
      requesting_user_id() = creator
      OR id IN (
        SELECT get_boards_for_authenticated_user()
      )
    );

DROP POLICY IF EXISTS "Users can update their boards" ON boards;
CREATE POLICY "Users can update their boards" ON boards FOR
    UPDATE USING (
      id IN (
        SELECT get_boards_for_authenticated_user()
      )
    );

DROP POLICY IF EXISTS "Users can delete their created boards" ON boards;
CREATE POLICY "Users can delete their created boards" ON boards FOR
    DELETE USING (requesting_user_id() = creator);

-- user_boards row level security
ALTER TABLE user_boards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can add their boards" ON user_boards;
CREATE POLICY "Users can add their boards" ON user_boards FOR
    INSERT TO public WITH CHECK (requesting_user_id() = user_id);

DROP POLICY IF EXISTS "Users can view boards" ON user_boards;
CREATE POLICY "Users can view boards"
ON user_boards
TO public
USING (true);

DROP POLICY IF EXISTS "Users can delete their boards" ON user_boards;
CREATE POLICY "Users can delete their boards" ON user_boards FOR
    DELETE USING (requesting_user_id() = user_id);

-- lists row level security
ALTER TABLE lists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can edit lists if they are part of the board" ON lists;
CREATE POLICY "Users can edit lists if they are part of the board" ON lists FOR
    ALL USING (
      board_id IN (
        SELECT get_boards_for_authenticated_user()
      )
    );

-- cards row level security
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can edit cards if they are part of the board" ON cards;
CREATE POLICY "Users can edit cards if they are part of the board" ON cards FOR
    ALL USING (
      board_id IN (
        SELECT get_boards_for_authenticated_user()
      )
    );

-- checklists row level security
ALTER TABLE checklists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can edit checklists if part of board" ON checklists;
CREATE POLICY "Users can edit checklists if part of board" ON checklists FOR ALL USING (
  card_id IN (SELECT id FROM cards WHERE board_id IN (SELECT get_boards_for_authenticated_user()))
);

-- checklist_items row level security
ALTER TABLE checklist_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can edit checklist items if part of board" ON checklist_items;
CREATE POLICY "Users can edit checklist items if part of board" ON checklist_items FOR ALL USING (
  checklist_id IN (SELECT id FROM checklists WHERE card_id IN (SELECT id FROM cards WHERE board_id IN (SELECT get_boards_for_authenticated_user())))
);

-- comments row level security
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can edit comments if part of board" ON comments;
CREATE POLICY "Users can edit comments if part of board" ON comments FOR ALL USING (
  card_id IN (SELECT id FROM cards WHERE board_id IN (SELECT get_boards_for_authenticated_user()))
);

-- labels row level security
ALTER TABLE labels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can edit labels if part of board" ON labels;
CREATE POLICY "Users can edit labels if part of board" ON labels FOR ALL USING (
  board_id IN (SELECT get_boards_for_authenticated_user())
);

-- card_labels row level security
ALTER TABLE card_labels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can edit card_labels if part of board" ON card_labels;
CREATE POLICY "Users can edit card_labels if part of board" ON card_labels FOR ALL USING (
  card_id IN (SELECT id FROM cards WHERE board_id IN (SELECT get_boards_for_authenticated_user()))
);

-- users row level security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view other users data" ON users;
CREATE POLICY "Users can view other users data"
ON users
TO public
USING (requesting_user_id() IS NOT NULL);

DROP POLICY IF EXISTS "Users can insert themselves" ON users;
CREATE POLICY "Users can insert themselves" ON users FOR
    INSERT TO public WITH CHECK (COALESCE(requesting_user_id(), id) = id);

DROP POLICY IF EXISTS "Users can update their own user" ON users;
CREATE POLICY "Users can update their own user" ON users FOR
    UPDATE USING (
      id = requesting_user_id()
    );

-- ============================================
-- 3. TRIGGERS
-- ============================================

-- Inserts a row into user_boards when a board is created
CREATE OR REPLACE FUNCTION public.handle_board_added()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.user_boards (board_id, user_id)
  VALUES (new.id, new.creator);
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_board_created ON boards;
CREATE TRIGGER on_board_created
  AFTER INSERT ON boards
  FOR EACH ROW EXECUTE PROCEDURE public.handle_board_added();

-- ============================================
-- 4. NOTIFICATIONS
-- ============================================

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    card_id BIGINT REFERENCES cards (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE OR REPLACE FUNCTION notify_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF new.assigned_to <> old.assigned_to THEN
    INSERT INTO notifications (user_id, body, card_id)
    VALUES (new.assigned_to, 'You have been assigned to a card!', new.id);
  END IF;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_card_assigned ON cards;
CREATE TRIGGER on_card_assigned
  BEFORE UPDATE ON cards
  FOR EACH ROW EXECUTE PROCEDURE notify_user();

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. SEARCH
-- ============================================

CREATE OR REPLACE FUNCTION public.search_users(search VARCHAR)
RETURNS SETOF users
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
    SELECT *
    FROM users u
    WHERE search % ANY(STRING_TO_ARRAY(u.email, ' '));
END;
$$;

-- ============================================
-- 6. STORAGE POLICY
-- ============================================
-- NOTE: You must first create a storage bucket named 'files'
-- in Supabase Dashboard -> Storage -> New bucket

DROP POLICY IF EXISTS "Protect storage access" ON storage.objects;
DROP POLICY IF EXISTS "nbt_tasker_storage_access" ON storage.objects;
CREATE POLICY "nbt_tasker_storage_access" ON storage.objects FOR ALL TO public USING (
  bucket_id = 'files'
  AND (storage.foldername(name))[1]::text ~ '^[0-9]+$'
  AND (storage.foldername(name))[1]::bigint IN (
    SELECT get_boards_for_authenticated_user()
  )
);
